// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nozxgiyyucuuzpoptjtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5venhnaXl5dWN1dXpwb3B0anRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMzODQsImV4cCI6MjA3MzExOTM4NH0.A95UbDgt3ho9pJvJ4RODP0VUgAUoD-gHR7DE531KUhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});